const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('minecraftLauncher', {
  fetchVersions: () => ipcRenderer.invoke('fetch-versions'),
  fetchInstalledVersions: () => ipcRenderer.invoke('fetch-installed-versions'),
  fetchAllVersions: () => ipcRenderer.invoke('fetch-all-versions'),
  fetchJava: () => ipcRenderer.invoke('fetch-java'),
  getVersionInfo: (versionId) => ipcRenderer.invoke('get-version-info', versionId),
  createModdedVersion: (payload) => ipcRenderer.invoke('create-modded-version', payload),
  renameModdedVersion: (payload) => ipcRenderer.invoke('rename-modded-version', payload),
  deleteModdedVersion: (payload) => ipcRenderer.invoke('delete-modded-version', payload),
  openVersionFolder: (payload) => ipcRenderer.invoke('open-version-folder', payload),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  searchModrinth: (payload) => ipcRenderer.invoke('search-modrinth', payload),
  searchModrinthShaders: (payload) => ipcRenderer.invoke('search-modrinth-shaders', payload),
  installMod: (payload) => ipcRenderer.invoke('install-mod', payload),
  listInstalledMods: (profileName) => ipcRenderer.invoke('list-installed-mods', profileName),
  removeMod: (payload) => ipcRenderer.invoke('remove-mod', payload),
  installResourcepack: (payload) => ipcRenderer.invoke('install-resourcepack', payload),
  installShader: (payload) => ipcRenderer.invoke('install-shader', payload),
  listInstalledResourcepacks: (profileName) => ipcRenderer.invoke('list-installed-resourcepacks', profileName),
  listInstalledShaders: (profileName) => ipcRenderer.invoke('list-installed-shaders', profileName),
  removeResourcepack: (payload) => ipcRenderer.invoke('remove-resourcepack', payload),
  removeShader: (payload) => ipcRenderer.invoke('remove-shader', payload),
  downloadVersion: (version) => ipcRenderer.invoke('download-version', version),
  launchGame: (payload) => ipcRenderer.invoke('launch-game', payload),
  fixVersion: (versionId) => ipcRenderer.invoke('fix-version', versionId),
  deleteVersion: (versionId) => ipcRenderer.invoke('delete-version', versionId),
  cancelPreparation: () => ipcRenderer.invoke('cancel-preparation'),
  fetchJson: (url) => ipcRenderer.invoke('fetch-json', url),
  onLog: (callback) => ipcRenderer.on('log', (_event, message) => callback(message)),
  onProgress: (callback) => ipcRenderer.on('progress', (_event, data) => callback(data)),
  onPreparationState: (callback) => ipcRenderer.on('preparation-state', (_event, isActive) => callback(isActive))
});
